FROM node:lts-alpine AS builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

RUN npm i -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN apk add --no-cache python3
RUN apk add --no-cache pkgconf cairo-dev jpeg-dev pango-dev giflib-dev build-base

# --production remove so that vite and its dependencies can build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

FROM nginx:alpine AS runner

ARG VERSION
ARG BUILD_TIME

ENV NODE_ENV=production
ENV VUE_APP_VERSION=$VERSION

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080