name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # - name: Lint & Format
      #   run: npm run lint

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
        with:
          commit-message: 'chore: apply automated updates'
