name: NPM CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm ci

      # - name: Lint & Format
      #   run: npm run lint

      - name: Test Types
        run: pnpm test:types

      - name: Bulid Artifacts
        run: pnpm build

      # - name: Run Tests
      #   run: pnpx vitest --coverage

      # - name: Upload Test Coverage
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
